# Generated by Django 5.1.7 on 2025-04-08 10:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="status",
            field=models.CharField(
                choices=[("active", "Active"), ("closed", "Closed")],
                default="closed",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="winner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="won_items",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
